
import type { Metadata } from "next";
import { Inter, Playfair_Display } from "next/font/google";
import "../styles/globals.scss";
import "../styles/reset.scss";
import clsx from "clsx";
import Header from "@/components/screens/Header/Header";
import Footer from "@/components/screens/Footer/Footer";
import LayoutStore from "@/components/layouts/LayoutStore";
import LayoutStateInit from "@/components/layouts/LayoutStateInit";


const playfair = Playfair_Display({
  variable: '--font-playfair',
  subsets: ['latin'],
  weight: ['400', '700'],
});

const inter = Inter({
  variable: '--font-inter',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body className={clsx(inter.variable, playfair.variable)}>
        <LayoutStore>
          <LayoutStateInit>
              
                {children}
              
            </LayoutStateInit>
         </LayoutStore>
         
       
        
      </body>
    </html>
  );
}
